# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if [ -f '/c/Users/josep/scoop/apps/miniconda3/current/Scripts/conda.exe' ]; then
    eval "$('/c/Users/josep/scoop/apps/miniconda3/current/Scripts/conda.exe' 'shell.bash' 'hook')"
fi
# <<< conda initialize <<<

