#!/usr/bin/env python3
"""Setup Splunk credentials for eclipse-splunk-investigation skill.

Stores SPLUNK_PASSWORD in OS keyring and creates .env file with
SPLUNK_HOST and SPLUNK_USERNAME.

Usage:
  Interactive:       python3 setup.py
  Non-interactive:   python3 setup.py --host HOST --username USER --password PASS
  Via env vars:      SPLUNK_HOST=HOST SPLUNK_USERNAME=USER SPLUNK_PASSWORD=PASS python3 setup.py
"""

import argparse
import getpass
import os
import sys
from pathlib import Path

import keyring

KEYRING_SERVICE = "eclipse-splunk-investigation"
DEFAULT_HOST = "splunk-awsprod.ezesoft.net"


def prompt_for_value(name: str, default: str | None = None, secure: bool = False) -> str:
    """Prompt user for a configuration value."""
    if secure:
        value = getpass.getpass(f"  {name}: ")
    else:
        prompt = f"  {name}"
        if default:
            prompt += f" (default: {default})"
        prompt += ": "
        value = input(prompt).strip()
        if not value and default:
            value = default
    return value


def create_env_file(host: str, username: str, skill_root: Path) -> None:
    """Create .env file with SPLUNK_HOST and SPLUNK_USERNAME."""
    env_file = skill_root / ".env"

    # Read existing .env if it exists to preserve other settings
    existing_lines = []
    if env_file.exists():
        with open(env_file) as f:
            for line in f:
                # Skip lines we're going to replace
                if not line.strip().startswith(("SPLUNK_HOST=", "SPLUNK_USERNAME=")):
                    existing_lines.append(line.rstrip())

    # Write new .env file
    with open(env_file, "w") as f:
        f.write("# Splunk Configuration\n")
        f.write("# Generated by setup.py\n")
        f.write("#\n")
        f.write("# SPLUNK_PASSWORD is stored securely in OS keyring, not in this file.\n")
        f.write("#\n\n")
        f.write(f'SPLUNK_HOST="{host}"\n')
        f.write(f'SPLUNK_USERNAME="{username}"\n')

        # Preserve other settings if they existed
        if existing_lines:
            f.write("\n# Other settings\n")
            for line in existing_lines:
                if line.strip():
                    f.write(line + "\n")

    # Set restrictive permissions
    env_file.chmod(0o600)
    print(f"\n✓ Created {env_file}")
    print("  (file permissions set to 600 for security)")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Setup Splunk credentials for eclipse-splunk-investigation skill."
    )
    parser.add_argument("--host", help="Splunk hostname (e.g., splunk-awsprod.ezesoft.net)")
    parser.add_argument("--username", help="Splunk username")
    parser.add_argument("--password", help="Splunk password")
    args = parser.parse_args()

    # Check if running interactively
    interactive = sys.stdin.isatty()

    # Try to load from environment variables if not provided
    host = args.host or os.environ.get("SPLUNK_HOST")
    username = args.username or os.environ.get("SPLUNK_USERNAME")
    password = args.password or os.environ.get("SPLUNK_PASSWORD")

    print("Eclipse Splunk Investigation - Credential Setup")
    print("=" * 50)
    print()
    print("This script will:")
    print("  1. Store SPLUNK_PASSWORD in OS keyring (secure)")
    print("  2. Create .env file with SPLUNK_HOST and SPLUNK_USERNAME")
    print()

    # Collect host
    if not host:
        if interactive:
            host = prompt_for_value("SPLUNK_HOST", default=DEFAULT_HOST)
        else:
            print("[error] SPLUNK_HOST not provided", file=sys.stderr)
            sys.exit(1)

    # Collect username
    if not username:
        if interactive:
            username = prompt_for_value("SPLUNK_USERNAME")
        else:
            print("[error] SPLUNK_USERNAME not provided", file=sys.stderr)
            sys.exit(1)

    if not username:
        print("[error] SPLUNK_USERNAME is required", file=sys.stderr)
        sys.exit(1)

    # Collect password
    if not password:
        if interactive:
            password = prompt_for_value("SPLUNK_PASSWORD", secure=True)
        else:
            print("[error] SPLUNK_PASSWORD not provided", file=sys.stderr)
            sys.exit(1)

    if not password:
        print("[error] SPLUNK_PASSWORD is required", file=sys.stderr)
        sys.exit(1)

    # Store password in keyring
    keyring.set_password(KEYRING_SERVICE, "SPLUNK_PASSWORD", password)
    print(f"\n✓ Stored SPLUNK_PASSWORD in keyring (service: {KEYRING_SERVICE})")

    # Create .env file
    skill_root = Path(__file__).parent.parent
    create_env_file(host, username, skill_root)

    print()
    print("─" * 50)
    print("Setup Complete!")
    print("─" * 50)
    print()
    print("Configuration loaded from:")
    print(f"  • OS Keyring: SPLUNK_PASSWORD")
    print(f"  • .env file:  SPLUNK_HOST, SPLUNK_USERNAME")
    print()
    print("You can now run queries:")
    print("  python3 scripts/splunk_query.py --service publisher --level ERROR")
    print()


if __name__ == "__main__":
    main()
